CREATE ROLE keycloak_user WITH
    NOSUPERUSER
    CREATEDB
    NOCREATEROLE
    INHERIT
    LOGIN
    REPLICATION
    NOBYPASSRLS
    CONNECTION LIMIT -1;

CREATE DATABASE keycloak_db WITH OWNER keycloak_user;


CREATE ROLE postgres WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    LOGIN
    NOREPLICATION
    NOBYPASSRLS
    CONNECTION LIMIT -1;

CREATE DATABASE postgres WITH OWNER postgres;
